apiVersion: v2
name: nginx-app
description: Nginx app
type: application
version: 0.1.0
dependencies:
  - name: base-chart
    version: "1.0.0"
    repository: "https://gowtham-reddy1198.github.io/helm-base-charts"
