apiVersion: v2
name: apps
description: App of Apps - generates ArgoCD applications
type: application
version: 0.1.0
dependencies:
  - name: apps
    version: "1.0.1"
    repository: "https://gowtham-reddy1198.github.io/helm-base-charts"
